#!/bin/sh

## place devices in ~/.config/btcon/devices.conf
## choose with fzf
## remember selection
## print info while connecting
## options to:
##  - connect
##  - disconnect
##  - change device
##  - turn off / on bluetooth
##  - scan, pair, trust and add to devices.conf with alias
##  - change / override number of tries (0 == infinite)
##  - tab completion
##  - print alignment
##  - multiple devices
##    - bluetoothctl can only control one device at a time
##      - use a loop

. "$XDG_CONFIG_HOME"/btcon/devices.conf || exit 1

CMD=connect

for opt; do
    if [ $opt = "-d" ]; then
        CMD=disconnect
    else
        eval "opt=\$$opt"
        SELECTION="$SELECTION $opt"
    fi
    unset opt
    shift
done

if [ -z $SELECTION ]; then
    SELECTION=$(printf "%s\n" "$DEVICES" | sed 's/=/ /' | fzf)
fi

bluetoothctl select $HOST || exit 1
bluetoothctl power on

tries=3
while [ $tries -gt 0 ]; do
	if ! bluetoothctl $CMD ${SELECTION#* }; then
		wait 2
		tries=$(( tries - 1 ))
	else
		break
	fi
done
