#!/bin/sh

config=/home/smtnskn/.config/dns/config
file=/etc/resolv.conf
[ "$1" ] || { grep nameserver "$file" | cut -d' ' -f2; exit; }
[ "$#" -gt 1 ] && { echo "Usage: ${0##*/} [ip address]"; exit; }

[ "$(id -u)" -ne 0 ] && { echo "Need root privileges"; exit 1; }

while read -r line; do
    [ "${line% *}" = "$1" ] && dns="${line#* }"
done < "$config"
[ "$dns" ] || dns="$1"

attrs=$(lsattr "$file" | cut -d' ' -f1 | tr -d '-' 2> /dev/null)
[ "$attrs" ] && chattr -"$attrs" "$file"
cat > $file <<EOF
search $(hostname | tr '[:upper:]' '[:lower:]').local
options edns0 single-request-reopen
nameserver $dns
EOF
[ "$attrs" ] && chattr +"$attrs" "$file"
