#!/bin/sh

config=/home/smtnskn/.config/dns/config
file=/etc/resolv.conf
[ "$1" ] || { grep nameserver "$file" | cut -d' ' -f2; exit; }
[ "$#" -gt 1 ] && { echo "Usage: ${0##*/} [ip address]"; exit; }

[ "$(id -u)" -ne 0 ] && { echo "Need root privileges"; exit 1; }

while read -r line; do
    [ "${line% *}" = "$1" ] && dns="${line#* }"
done < "$config"
[ "$dns" ] || dns="$1"

attrs=$(lsattr "$file" | cut -d' ' -f1 | tr -d '-')
[ "$attrs" ] && chattr -"$attrs" "$file"
printf "%s\n" "$(sed "s/nameserver.*/nameserver $dns/" "$file")" > "$file"
[ "$attrs" ] && chattr +"$attrs" "$file"
