#!/bin/sh

format="%-9s %s\n"

du -sk -d1 "$@" | sort -nr | while read -r line; do
	set -- $line
	kb="$1"
	shift
	folder="$*"

	folder=${folder#${folder%%[![:space:]]*}}  # Trim leading whitespace
	folder=${folder#./}  # Trim leading './'

	if [ "$kb" -lt 1000 ]; then
		printf "$format" "$kb"K "$folder"
	elif [ "$kb" -lt 1000000 ]; then
		mb=$(printf "scale=2; %s/1000" "$kb" | bc)
		printf "$format" "$mb"M "$folder"
	else
		gb=$(printf "scale=2; %s/1000000" "$kb" | bc)
		printf "$format" "$gb"G "$folder"
	fi

	# unset folder
	folder=
done
