#!/bin/sh

## https://owasp.org/www-community/password-special-characters

shuffle() { printf "%s" "$1" | fold -w1 | shuf | tr -d '\n'; }

letter_n=12
number_n=3
special_n=3

number_str=$(seq 0 9 | shuf | tr -d '\n' | cut -c -${number_n})
letter_str=$(shuffle "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" \
	| cut -c -${letter_n})
special_str=$(shuffle "!\"#$%&'()*+,-./:;<=>?@[\\]^_\`{|}~" | cut -c -${special_n})

printf "%s\n" $(shuffle "${number_str}${letter_str}${special_str}")
