#!/bin/sh

## A hack to redirect the output of a program that lacks logging facilities
## to a file (give me those sweet, sweet logs, smtpd)

if [ "$1" = "-d" ]; then
	shift
	exec >> "$@"
	while read -r line; do
		printf "%s\n" "$(date +'%Y-%m-%d %H:%M:%S'): $line"
	done
else
	exec >> "$@"
	while read -r line; do
		printf "%s\n" "$line"
	done
fi
