#!/bin/sh

_pwd="$PWD"
[ "$_pwd" ] || _pwd="$(pwd)"

case "$_pwd" in
	"$HOME"*) _pwd="~${_pwd#*${HOME}}" ;;
	*) : ;;
esac

_pwd="$(printf "%s" "$_pwd" | sed 's:\([^/]\)[^/]*/:\1/:g')"

[ "$(id -u)" -eq 0 ] && is_root=1
if [ "$SSH_TTY" ]; then
	if [ "$is_root" ]; then
		PS1='\[\e]0;\W\a\033[1;31m\]\h:$_pwd #\[\033[00m\] '
	else
		PS1='\[\e]0;\W\a\033[1;36m\]\h:$_pwd $\[\033[00m\] '
	fi
elif [ "$is_root" ]; then
	PS1='\[\e]0;\W\a\033[1;31m\]$_pwd #\[\033[00m\] '
else
	PS1='\[\e]0;\W\a\033[1;36m\]$_pwd $\[\033[00m\] '
fi
