#!/bin/sh

fields="$(rbw ls --fields folder,name,user | \
	sed 's/^[\t ]*//; s/\t/ | /' | \
	rofi -dmenu -matching fuzzy -sort -i | \
	sed 's/ |//' | \
	xargs -r rbw get --full)"

printf "%s" "$fields" | sed q | tr -d '\n' | xsel -ip -t 30000
printf "%s" "$fields" | awk '/Username/ {print $2;}' | tr -d '\n' | xsel -ib -t 30000

# password=$(printf "%s" "$fields" | sed q)
# username=$(printf "%s" "$fields" | awk '/Username/ {print $2;}')
# uri=$(printf "%s" "$fields" | awk '/URI/ {print $2;}')
# totp=$(printf "%s" "$fields" | awk '/TOTP/ {print $3;}')

# wid=$(xdotool getactivewindow)
# xdotool type --window $wid $username
# xdotool key KP_Tab
# xdotool type --window $wid $password
# xdotool type $(oathtool --totp -b $totp)
