#!/bin/sh

[ "$(id -u)" -ne 0 ] && { printf "Need root\n"; exit 1; }

kexec -l /boot/vmlinuz-lts --initrd /boot/initramfs-lts --reuse-cmdline \
    && openrc shutdown
modprobe -r amdgpu \
    && kexec -e
