#!/bin/sh

## rp for replicate; WIP

## TODO:
##   - do getopts and pass marked options to external commands
##   - default options for external commands
##   - select entries from $entries_f with fzf for replication
##   - export to $entries_f with a single command
##   - store by default if no entries; ask for action (c|m|e) otherwise
##   - choose files with fzf !!

usage="Usage: ${0##*/} -s <files> -cmlre"

die() {
	[ "$1" ] && printf "%s\n" "$1"
	exit 1
}

replicate() {
	entries="$(wc -l "$entries_f" | awk '{print $1}')"
	fails=0
	action="Copied"
	[ "$1" = "mv" ] && action="Moved"

	while read -r entry; do
		"$@" "$entry" . || printf "%s\n" "$entry" >> "$fails_f"
	done < "$entries_f"

	if [ -e "$fails_f" ]; then
		fails="$(wc -l "$fails_f" | awk '{print $1}')"
		chmod 600 "$fails_f"
		mv -f "$fails_f" "$entries_f"
	else
		rm "$entries_f"
	fi

	printf "%s: %d/%d\n" "$action" "$(( entries - fails ))" "$entries"
}

[ "$1" ] || die "$usage"

entries_f="${TMPDIR:-${TMP:-/tmp}}"/"${0##*/}"_entries.txt
fails_f="${TMPDIR:-${TMP:-/tmp}}"/"${0##*/}"_fails.txt

cmd="$1"
shift
case "$cmd" in
	"-s")  ## store
		[ "$1" ] || die "$usage"
		entries="$#"
		if [ -e "$entries_f" ]; then
			if [ ! -w "$entries_f" ]; then
				printf "%s\n" "$entries_f is not writable and will be replaced."
				rm "$entries_f" || die
				touch "$entries_f" || die
				chmod 600 "$entries_f"
			else
				entries="$(wc -l "$entries_f" | awk '{print $1}') + $entries"
			fi
		fi

		pwd=$(pwd)
		for entry; do
			printf "%s\n" "${pwd}/${entry}" >> "$entries_f"
		done

		printf "Stored: %s\n" "$entries"
		;;
	"-c")  ## copy
		replicate cp
		;;
	"-m")  ## move
		replicate mv
		;;
	"-l")  ## list
		cat "$entries_f"
		;;
	"-r")  ## remove
		rm -v "$entries_f"
		;;
	"-e")  ## edit
		exec ${EDITOR:-vi} "$entries_f"
		;;
	*) die "$usage" ;;
esac
