#!/bin/sh

export FZF_DEFAULT_OPTS="--height 30% --reverse"

die()
{
    usage="\
Usage:
  ${0##*/} -mu [-p <path>] [-t <host>]

Options:
  -m --mount
  -u --umount
  -p --path    mount point for sshfs host
               defaults to '/media/<host>'
  -t --target  sshfs host name or address
               defaults to interactively selecting one from '~/.ssh/config'"

    printf "%s\n" "${1:-$usage}"
    exit 1
}

_mount()
{
    [ -d "$path" ] || { mkdir "$path" || exit 1; }
    chown root:wheel "$path"
    chmod 770 "$path"
    sshfs -o allow_other,workaround=renamexdev "$host":/ "$path"
}
_umount() { umount "$path" && rmdir "$path"; }

[ "$(id -u)" -ne 0 ] && die "Need root privileges"
[ "$1" ] || die

while getopts mup:t:-: opt; do
    case $opt in
        m) mount=1 ;;
        u) umount=1 ;;
        p) path="$OPTARG" ;;
        t) host="$OPTARG" ;;
        -)
            case $OPTARG in
                mount) mount=1 ;;
                umount) umount=1 ;;
                path) path="$OPTARG" ;;
                target) host="$OPTARG" ;;
                *) die ;;
            esac
            ;;
        *) die ;;
    esac
done
mount_root=/media
[ "$host" ] || host=$(awk '/^Host/ {print $2}' ~/.ssh/config | fzf)
[ "$path" ] || path="$mount_root"/"$host"
[ "$path" = "$mount_root"/ ] && { die "No host given"; }

if [ "$mount" ]; then
    _mount
elif [ "$umount" ]; then
    _umount
else
    die
fi
