#!/bin/sh

max=0
while : ; do
	cur=$(sensors k10temp-pci-00c3 | awk '/Tctl/ {print $2}' | grep -o "[0-9.]*")
	if [ $(printf "%s > %s" "$cur" "$max" | bc) -eq 1 ]; then
		max=$cur
	fi
	printf "max temp: %s°C\r" "$max"
	sleep 2
done
